Bugfix: Files missing from packaged wheel
This PR fixes packaging as the `__init__.py` file was not included since have `packages = find:` in the `setup.cfg` file.

We currently see the following error with the 1.0.0 version of this package that is installed in the runtime image.
```
>>> from astronomer_operators.databricks.hooks.databricks import DatabricksHookAsync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/astronomer_operators/databricks.py", line 13, in <module>
    from astronomer_operators.hooks.databricks import DatabricksHookAsync
ModuleNotFoundError: No module named 'astronomer_operators.hooks'
```

I am also removing some of the deprecatino since obviously the "hooks" folder wasn't included and HTTP wasn't included too, so just some cleanup.